In [419]:
#mounting Gdrive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [420]:
import pandas as pd
import numpy as np
from datetime import date, datetime
import holidays
import matplotlib.pyplot as plt
from IPython.display import display
pd.options.display.max_columns = None

In [421]:
##Wrangling Helper Functions to Use
"""
This function do the reading of data file from file path(i.e drive)
"""
def do_read_data(datafile, dateCol):
    ''' Read the excel file'''
    df = pd.read_excel(datafile, index_col= dateCol, parse_dates=True)
    return df

"""
This function Shows Information of the Data file
Like The Header columns, Dimension of Data
"""

def do_data_information(datafile, info = False, head = True, shape = True):
    ''' Look at the info of the data'''
    
    if not isinstance(datafile, pd.DataFrame):
        df = read_data(datafile)
    else:
        df = datafile
    
    ## Information of data
    if info:
        df.info()
        
    print('--------------------------------------------------------------------')
    print('First rows')
    # Show first rows
    if head:
        print(df.head())
        
    print('--------------------------------------------------------------------')
    print('Dimension of the data')
    ## Dimension of data
    if shape:
        print(f'This data has {df.shape[0]} rows and {df.shape[1]} variables') 
        
###This function returns the number of distinct values from any columns       
def do_unique_values(df, col):
    ''' Find the unique values of a columns'''
    return df[col].nunique()


###This function statistically describe the data values
def do_description(df, col = None):
    ''' Give the statistic summary'''
    
    ## Summary statistic
    if col is not None:
        stat = df[col].describe()
    else:
        stat = df.describe()

    ## Change the name of the 50% index to median
    idx = stat.index.tolist()
    idx[5] = 'median'
    stat.index = idx
    return stat

###This function finds % Missing values
def check_missing_value(data):
    ## percentage of missing values
    n = data.isnull().sum().sort_values(ascending=False)/ len(data) * 100
    return n

def check_missing_values_table(df):
  mis_val = df.isnull().sum()
  mis_val_percent = 100 * df.isnull().sum() / len(df)
  mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
  mis_val_table_ren_columns = mis_val_table.rename(
  columns = {0 : 'Missing Values', 1 : '% of Total Values'})
  mis_val_table_ren_columns = mis_val_table_ren_columns[
      mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
  '% of Total Values', ascending=False).round(1)
  print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
      "There are " + str(mis_val_table_ren_columns.shape[0]) +
        " columns that have missing values.")
  return mis_val_table_ren_columns


###This function finds the amount of each values in a dataset
def do_valueCount(data, col, perc = False):
    ''' calculate the proportion in fraction or percentage'''
    if not perc:
      return data[col].value_counts()
    else:
      return data[col].value_counts(normalize = True).mul(100).round(1).astype(str) + '%'    
### This function count number of unique values for all columns in a dataset
def do_nunique_value(df):
  print('The Numver of unique values per columns are as follows')
  print(df.agg(['nunique']).T)


###For date time conversion start here   
def do_date_col_convertion(df, column_name):
  df[column_name]=pd.to_datetime(df[column_name])
  return df[column_name]

def do_time_col_convertion(df, column_name):
    return pd.to_timedelta(df[column_name])


def do_datepart_extraction(data):
  data['date'] = pd.to_datetime(data['date'])
  data['dateOnly']=data['date'].dt.date
  data['year'] = data['date'].dt.year
  data['quarter']=data['date'].dt.quarter
  data['month'] = data['date'].dt.month
  data['weekday'] = data['date'].dt.weekday
  data['day_name'] = data['date'].dt.day_name()
  data['dayofyear'] = data['date'].dt.dayofyear
  data['day'] =data['date'].dt.day
  data['hour'] = data['date'].dt.hour
  data['minute'] =data['date'].dt.minute
  #data['Season']=data['month'].apply(do_year_season)
  data['season'] = data.date.map(do_season_of_date)
  data['day_section']=data['hour'].apply(do_day_sections)
  return data
   

def do_season_of_date(date):
  year = str(date.year)
  seasons = {'spring': pd.date_range(start='21/03/'+year, end='20/06/'+year),
              'summer': pd.date_range(start='21/06/'+year, end='22/09/'+year),
              'autumn': pd.date_range(start='23/09/'+year, end='20/12/'+year)}
  if date in seasons['spring']:
    return 'spring'
  if date in seasons['summer']:
    return 'summer'
  if date in seasons['autumn']:
    return 'autumn'
  else:
    return 'winter'

# Assuming df has a date column of type `datetime`
#df['season'] = df.date.map(season_of_date)


def do_day_sections(x):
  if (x > 4) and (x <= 8):
    return 'Early Morning'
  elif (x > 8) and (x <= 12 ):
    return 'Morning'
  elif (x > 12) and (x <= 16):
    return'Noon'
  elif (x > 16) and (x <= 20) :
    return 'Evening'
  elif (x > 20) and (x <= 24):
    return'Night'
  elif (x <= 4):
    return'Late Night'




def get_holidays(startYear = 2018, endYear = 2025, countryCode = 'ZA'):
  """
    Takes in a start and end date, and start and end year.
    
    Produces a dataframe with a daily date and columns:
    holiday - 'Y' for holiday
    holidayName - name of the holiday if holiday is 'Y'
    
    Returns a dataframe
  """
  holidayDict = {}
  for i in range(startYear, endYear):
    for date, name in sorted(holidays.CountryHoliday(countryCode,years=[i]).items()):
      holidayDict[date] = name
      holiday_df = pd.DataFrame(list(holidayDict.items()),columns = ['day','holidayName'])
      holiday_df['day'] = pd.to_datetime(holiday_df['day'], format='%Y-%M-%d').dt.date
    return holiday_df
    

    
def get_days(start = '1/1/2018',startYear = 2018, end = '31/12/2025',endYear = 2025, countryCode = 'ZA'):
    """
    Takes in a start and end date, and start and end year.
    
    Produces a dataframe with a daily date and columns:
    weekend - 'Y' for weendend and 'N' for workday
    dayOfweek - numerical day of the week identifier 0 for monday
    weekNum - numerical number of the week 
    holiday - 'Y' for holiday
    holidayName - name of the holiday if holiday is 'Y'
    
    Returns a dataframe
    """
    
    #generate the range of daily dates
    dates = pd.date_range(start = start, end = end)
    date_df = pd.DataFrame(dates, columns = ['day'])
    date_df['day'] = pd.to_datetime(date_df['day'], format='%Y-%M-%d')
    country_holidays = get_holidays(startYear = startYear, endYear = endYear, countryCode = countryCode)
    
    date_df['dayName'] = pd.DatetimeIndex(date_df['day']).day_name()
    date_df['dayOfWeek'] = date_df['day'].dt.dayofweek
    date_df['weekend'] = date_df['dayOfWeek'].apply(lambda x: 'Y' if x>4 else 'N')
    date_df['weekNum'] = date_df['day'].dt.week
    date_df['holiday'] = date_df['day'].apply(lambda x: 'Y' if x in country_holidays['day'].values else 'N')
    date_df['day'] = date_df['day'].dt.date
    date_df = date_df.merge(country_holidays, on='day', how='left', indicator=False)
    
    date_df.to_csv(f'../data/public_holidays_weekends.csv', index=False)
    return date_df

###Functions to impute nan values for numerical varriable
def Impute_nan(df):
  numericalcol = [f for f in df_5min.columns if df_5min.dtypes[f] != 'object']
  missing_col=df_5min[numericalcol].columns[df_5min[numericalcol].isnull().any()].tolist()
  #Technique 1: Using mean to impute the missing values
  for i in missing_col:
    df.loc[df.loc[:,i].isnull(),i]=df.loc[:,i].mean()

def Impute_na(df):
  numericalcol = [f for f in df_5min.columns if df_5min.dtypes[f] != 'object']
  missing_col=df_5min[numericalcol].columns[df_5min[numericalcol].isnull().any()].tolist()
  #Technique 1: Using mean to impute the missing values
  for i in missing_col:
     df[i].fillna(mean,inplace=True)


#dataList=[df_5min,df_hourly,df_daily,df_monthly]

def do_wrangling_task(dL):
  for i in range(len(dL)):
    print(do_data_information(dL[i]))
    print('===============================================')
    print(check_missing_values_table(dL[i]))
    print('===============================================')
    print(do_nunique_value(dL[i]))
    print('===============================================')
    #Feature Engineering
    dL[i]=do_datepart_extraction(dL[i])
    print('===============================================')
    dL[i].date.min(),dL[i].date.max()
    print('===============================================')
    dL[i].consumption.min(),dL[i].consumption.max()
    print('===============================================')
    #checking for days where there weere no consumptions
    dL[i][dL[i].consumption==0].value_counts().count(),dL[i][dL[i].consumption==0].value_counts()
    print('===============================================')
    dL[i]['Public_Holiday'] = dL[i]['dateOnly'].map(mapping)
    print('===============================================')
    dL[i]['Public_Holiday']=dL[i]['Public_Holiday'].apply(lambda x:np.NaN if isinstance(x, str) and (x.isspace() or not x) else x).replace(np.NaN,'Non_Holiday')
    print('===============================================')
    dL[i]=dL[i][['date','timestamp','year','quarter','month','dayofyear','day','day_name','hour','minute','season','day_section','Public_Holiday','consumption','solar','alwaysOn','gridImport','gridExport','selfConsumption','selfSufficiency','active','reactive','voltages','phaseVoltages','currentHarmonics','voltageHarmonics']]
    print('===============================================')
    print('===============================================')

# load helper functions for dynamic import
def import_package(name):
    try:
        module = __import__(name)
    except:
        if name == 'pandas_profiling':
          ! pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip
        module = __import__(name)
    try:
        print(f'{name}'+ ' Version:', module.__version__)
    except AttributeError:
        pass
    return module


# JMcQ
def plot_period(df, date1, date2, column, title):
    
    df = df.loc[date1:date2]
    
    fig, axs = plt.subplots(1,1, figsize = (12, 6))
    
    fig.suptitle(title)
    
    x = df['datetime']
    
    axs.plot(x, df[column], label=column)
    axs.legend(loc="best")

    plt.show()

# JMcQ
def create_monthly_profiles(df, column):
    
    months = df['monthName'].unique()
    
    df = df.groupby([df['weekend'], df['monthName'], df['hour']]).mean()
       
    fig, axs = plt.subplots(1, 2, figsize=(10,6), sharey=True, sharex=True)
    
    fig.suptitle('Weekend and Weekday Profiles')
    
    x = list(range(0,24))
    plt.xticks(x)
    
    # Loop through each month of the year and plot profile
    for month in months:
        
        axs[0].plot(x, df.loc[0, month][column], label=month)
        axs[0].legend(loc="best")
        axs[0].set_title('Weekday')

        axs[1].plot(x, df.loc[1, month][column], label=month)
        axs[1].legend(loc="best")
        axs[1].set_title('Weekend')
        
            
    plt.show()
    
    return df

def load_data(file):
    df = pd.read_csv(file)
    df = df.astype({'date':'datetime64[ns]'})
    df.sort_values(by='date', inplace=True)
    return df

#df['holidays']=df['date'].apply(lambda(x: 'Hols' if x in get_holidays()['day'].values else 'Non-Hols'))

In [422]:
asset = "/content/drive/MyDrive/NEEDENERGY/data_five_min_id_47803.csv"

In [423]:
pd = import_package('pandas')
profile = import_package('pandas_profiling')
np = import_package('numpy')
tz = import_package('dateutil').tz
datetime = import_package('datetime').datetime

pandas Version: 1.1.5
numpy Version: 1.19.5
dateutil Version: 2.8.1

In [424]:
df_5min = load_data(asset)

In [425]:
df_5min.head()

,date,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-15 18:15:00,1584288900000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.1, 3.7, 0.0, -81.6, -60.0, 30.2, -230.6, -0...","[0.5, 0.9, 0.0, 55.4, 132.4, 14.0, 137.5, 0.2,...","[244.5, None, None]","[244.5, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-03-15 18:20:00,1584289200000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.1, 3.8, 0.0, -82.2, -58.5, 30.5, -233.1, -0...","[0.5, 0.9, 0.0, 55.7, 131.9, 14.3, 144.3, 0.2,...","[246.1, None, None]","[246.1, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,2020-03-15 18:25:00,1584289500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.1, 28.5, -26.5, -74.4, -79.2, 55.5, -228.5,...","[0.5, 19.0, 8.8, 79.6, 137.6, 29.4, 175.0, 0.4...","[246.4, None, None]","[246.4, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
3,2020-03-15 18:30:00,1584289800000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.5, 21.3, -18.6, -76.9, -54.7, 48.7, -227.8,...","[2.2, 13.3, 6.5, 72.4, 135.9, 24.8, 152.8, 0.8...","[246.0, None, None]","[246.0, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
4,2020-03-15 18:35:00,1584290100000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.1, 3.7, 0.0, -82.6, -33.2, 30.7, 96.6, 0.2,...","[0.5, 0.9, 0.0, 55.2, 128.1, 13.9, 87.7, 0.7, ...","[246.2, None, None]","[246.2, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

Data Quality Information:
df_5min : The data has 95649 rows and 15 features

In [426]:
#basic profiling
df_5min.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95649 entries, 0 to 95648
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              95649 non-null  datetime64[ns]
 1   timestamp         95649 non-null  int64
 2   consumption       95649 non-null  float64
 3   solar             95649 non-null  float64
 4   alwaysOn          95649 non-null  float64
 5   gridImport        95649 non-null  float64
 6   gridExport        95649 non-null  float64
 7   selfConsumption   95649 non-null  float64
 8   selfSufficiency   95649 non-null  float64
 9   active            95649 non-null  object
 10  reactive          95649 non-null  object
 11  voltages          95649 non-null  object
 12  phaseVoltages     95649 non-null  object
 13  currentHarmonics  95649 non-null  object
 14  voltageHarmonics  95649 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(1), object(6)
memory usage: 11.7+ MB

In [427]:
#statistcal summary
df_5min.describe

<bound method NDFrame.describe of                      date      timestamp  consumption   solar  alwaysOn  \
0     2020-03-15 18:15:00  1584288900000        0.000   0.000     0.000
1     2020-03-15 18:20:00  1584289200000        0.000   0.000     0.000
2     2020-03-15 18:25:00  1584289500000        0.000   0.000     0.000
3     2020-03-15 18:30:00  1584289800000        0.000   0.000     0.000
4     2020-03-15 18:35:00  1584290100000        0.000   0.000     0.000
...                   ...            ...          ...     ...       ...
95644 2021-02-12 01:35:00  1613086500000      191.070  41.140  1006.212
95645 2021-02-12 01:40:00  1613086800000      166.362  47.789  1006.212
95646 2021-02-12 01:45:00  1613087100000      155.303  41.008  1006.212
95647 2021-02-12 01:50:00  1613087400000      156.402  48.199  1006.212
95648 2021-02-12 01:55:00  1613087700000      153.934  46.152  1006.212

       gridImport  gridExport  selfConsumption  selfSufficiency  \
0           0.000         0.0              0.0             0.00
1           0.000         0.0              0.0             0.00
2           0.000         0.0              0.0             0.00
3           0.000         0.0              0.0             0.00
4           0.000         0.0              0.0             0.00
...           ...         ...              ...              ...
95644     149.930         0.0            100.0            21.53
95645     118.572         0.0            100.0            28.73
95646     114.294         0.0            100.0            26.41
95647     108.203         0.0            100.0            30.82
95648     107.781         0.0            100.0            29.98

                                                  active  \
0      [0.1, 3.7, 0.0, -81.6, -60.0, 30.2, -230.6, -0...
1      [0.1, 3.8, 0.0, -82.2, -58.5, 30.5, -233.1, -0...
2      [0.1, 28.5, -26.5, -74.4, -79.2, 55.5, -228.5,...
3      [0.5, 21.3, -18.6, -76.9, -54.7, 48.7, -227.8,...
4      [0.1, 3.7, 0.0, -82.6, -33.2, 30.7, 96.6, 0.2,...
...                                                  ...
95644  [0.1, 3.6, -0.1, None, None, None, None, 0.4, ...
95645  [0.1, 3.6, -0.1, None, None, None, None, 0.4, ...
95646  [0.2, 3.6, -0.1, None, None, None, None, 1.3, ...
95647  [0.3, 3.6, -0.1, None, None, None, None, 0.6, ...
95648  [0.1, 3.6, -0.1, None, None, None, None, 0.4, ...

                                                reactive             voltages  \
0      [0.5, 0.9, 0.0, 55.4, 132.4, 14.0, 137.5, 0.2,...  [244.5, None, None]
1      [0.5, 0.9, 0.0, 55.7, 131.9, 14.3, 144.3, 0.2,...  [246.1, None, None]
2      [0.5, 19.0, 8.8, 79.6, 137.6, 29.4, 175.0, 0.4...  [246.4, None, None]
3      [2.2, 13.3, 6.5, 72.4, 135.9, 24.8, 152.8, 0.8...  [246.0, None, None]
4      [0.5, 0.9, 0.0, 55.2, 128.1, 13.9, 87.7, 0.7, ...  [246.2, None, None]
...                                                  ...                  ...
95644  [-0.4, 0.9, 0.0, None, None, None, None, -0.2,...  [241.2, None, None]
95645  [-0.4, 0.9, 0.0, None, None, None, None, -0.2,...  [241.1, None, None]
95646  [-0.9, 0.9, 0.0, None, None, None, None, -0.5,...  [241.3, None, None]
95647  [-1.3, 0.8, 0.0, None, None, None, None, -0.3,...  [241.2, None, None]
95648  [-0.4, 0.8, 0.0, None, None, None, None, -0.2,...  [240.9, None, None]

             phaseVoltages                                   currentHarmonics  \
0      [244.5, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
1      [246.1, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
2      [246.4, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
3      [246.0, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
4      [246.2, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
...                    ...                                                ...
95644  [241.2, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
95645  [241.1, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
95646  [241.3, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
95647  [241.2, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
95648  [240.9, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...

                                        voltageHarmonics
0      [[], [], [], [], [], [], [], [], [], [], [], [...
1      [[], [], [], [], [], [], [], [], [], [], [], [...
2      [[], [], [], [], [], [], [], [], [], [], [], [...
3      [[], [], [], [], [], [], [], [], [], [], [], [...
4      [[], [], [], [], [], [], [], [], [], [], [], [...
...                                                  ...
95644  [[], [], [], [], [], [], [], [], [], [], [], [...
95645  [[], [], [], [], [], [], [], [], [], [], [], [...
95646  [[], [], [], [], [], [], [], [], [], [], [], [...
95647  [[], [], [], [], [], [], [], [], [], [], [], [...
95648  [[], [], [], [], [], [], [], [], [], [], [], [...

[95649 rows x 15 columns]>

In [428]:
#List of features
df_5min.columns

Index(['date', 'timestamp', 'consumption', 'solar', 'alwaysOn', 'gridImport',
       'gridExport', 'selfConsumption', 'selfSufficiency', 'active',
       'reactive', 'voltages', 'phaseVoltages', 'currentHarmonics',
       'voltageHarmonics'],
      dtype='object')

In [429]:
#profile.ProfileReport(df_5min)
#!pip install pandas-profiling[notebook]

In [430]:

#profile.ProfileReport(df_5min)

In [431]:
df_5min_new = df_5min.copy()

In [432]:
df_5min_new.head()

,date,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-15 18:15:00,1584288900000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.1, 3.7, 0.0, -81.6, -60.0, 30.2, -230.6, -0...","[0.5, 0.9, 0.0, 55.4, 132.4, 14.0, 137.5, 0.2,...","[244.5, None, None]","[244.5, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-03-15 18:20:00,1584289200000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.1, 3.8, 0.0, -82.2, -58.5, 30.5, -233.1, -0...","[0.5, 0.9, 0.0, 55.7, 131.9, 14.3, 144.3, 0.2,...","[246.1, None, None]","[246.1, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,2020-03-15 18:25:00,1584289500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.1, 28.5, -26.5, -74.4, -79.2, 55.5, -228.5,...","[0.5, 19.0, 8.8, 79.6, 137.6, 29.4, 175.0, 0.4...","[246.4, None, None]","[246.4, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
3,2020-03-15 18:30:00,1584289800000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.5, 21.3, -18.6, -76.9, -54.7, 48.7, -227.8,...","[2.2, 13.3, 6.5, 72.4, 135.9, 24.8, 152.8, 0.8...","[246.0, None, None]","[246.0, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
4,2020-03-15 18:35:00,1584290100000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.1, 3.7, 0.0, -82.6, -33.2, 30.7, 96.6, 0.2,...","[0.5, 0.9, 0.0, 55.2, 128.1, 13.9, 87.7, 0.7, ...","[246.2, None, None]","[246.2, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

In [433]:
#Check for duplicates
df_5min_new.index[df_5min_new['date'].duplicated(keep=False)==True]

Int64Index([], dtype='int64')

In [434]:
# Check for missing info using Missingno Package
msno = import_package('missingno')
msno.matrix(df_5min_new)

missingno Version: 0.4.2

In [435]:
# Check if there are any periods of zero values
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
features = df_5min_new.select_dtypes(include=numerics).columns 
for feature in features: 
    zero_results = df_5min_new[df_5min_new[feature]==0]
zero_results.head()

,date,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-15 18:15:00,1584288900000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.1, 3.7, 0.0, -81.6, -60.0, 30.2, -230.6, -0...","[0.5, 0.9, 0.0, 55.4, 132.4, 14.0, 137.5, 0.2,...","[244.5, None, None]","[244.5, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-03-15 18:20:00,1584289200000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.1, 3.8, 0.0, -82.2, -58.5, 30.5, -233.1, -0...","[0.5, 0.9, 0.0, 55.7, 131.9, 14.3, 144.3, 0.2,...","[246.1, None, None]","[246.1, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,2020-03-15 18:25:00,1584289500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.1, 28.5, -26.5, -74.4, -79.2, 55.5, -228.5,...","[0.5, 19.0, 8.8, 79.6, 137.6, 29.4, 175.0, 0.4...","[246.4, None, None]","[246.4, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
3,2020-03-15 18:30:00,1584289800000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.5, 21.3, -18.6, -76.9, -54.7, 48.7, -227.8,...","[2.2, 13.3, 6.5, 72.4, 135.9, 24.8, 152.8, 0.8...","[246.0, None, None]","[246.0, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
4,2020-03-15 18:35:00,1584290100000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"[0.1, 3.7, 0.0, -82.6, -33.2, 30.7, 96.6, 0.2,...","[0.5, 0.9, 0.0, 55.2, 128.1, 13.9, 87.7, 0.7, ...","[246.2, None, None]","[246.2, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

In [436]:
# Check for any missing time steps, create hourly datetime index and compare to length of dataframe
start = df_5min_new['date'].min()
end = df_5min_new['date'].max()
full_index = pd.date_range(start, end, freq='H')
len(full_index) == len(df_5min_new)

False

In [437]:
df_5min_new.set_index('date', inplace = True)
df_5min_new = df_5min_new.reindex(full_index)
df_5min_new.index

DatetimeIndex(['2020-03-15 18:15:00', '2020-03-15 19:15:00',
               '2020-03-15 20:15:00', '2020-03-15 21:15:00',
               '2020-03-15 22:15:00', '2020-03-15 23:15:00',
               '2020-03-16 00:15:00', '2020-03-16 01:15:00',
               '2020-03-16 02:15:00', '2020-03-16 03:15:00',
               ...
               '2021-02-11 16:15:00', '2021-02-11 17:15:00',
               '2021-02-11 18:15:00', '2021-02-11 19:15:00',
               '2021-02-11 20:15:00', '2021-02-11 21:15:00',
               '2021-02-11 22:15:00', '2021-02-11 23:15:00',
               '2021-02-12 00:15:00', '2021-02-12 01:15:00'],
              dtype='datetime64[ns]', length=8000, freq='H')

In [438]:
#Have a look at missing values
print(f"{df_5min_new.isnull().sum()}\n\n")
print(f"Percentage of missing values:\t{(df_5min_new['consumption'].isnull().sum()/df_5min_new['timestamp'].count())*100}")

timestamp           28
consumption         28
solar               28
alwaysOn            28
gridImport          28
gridExport          28
selfConsumption     28
selfSufficiency     28
active              28
reactive            28
voltages            28
phaseVoltages       28
currentHarmonics    28
voltageHarmonics    28
dtype: int64


Percentage of missing values:	0.35122930255895635

Feature Engineering Time Series

In [439]:
df_5min_new.reset_index(inplace=True)
df_5min_new.rename(columns = {'index':'datetime'}, inplace = True)
df_5min_new.head()

,datetime,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-15 18:15:00,1.584289e+12,0.000,0.0,0.0,0.000,0.0,0.0,0.0,"[0.1, 3.7, 0.0, -81.6, -60.0, 30.2, -230.6, -0...","[0.5, 0.9, 0.0, 55.4, 132.4, 14.0, 137.5, 0.2,...","[244.5, None, None]","[244.5, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-03-15 19:15:00,1.584292e+12,35.615,0.0,0.0,35.615,0.0,0.0,0.0,"[0.1, 20.3, 0.0, None, 0.0, 47.0, 237.2, 0.3, ...","[0.5, 1.9, 0.0, None, 0.1, 13.6, 155.9, 0.2, N...","[247.3, None, None]","[247.3, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,2020-03-15 20:15:00,1.584296e+12,49.976,0.0,0.0,49.976,0.0,0.0,0.0,"[0.1, 3.8, 0.0, None, None, 33.4, 117.8, 0.4, ...","[0.5, 0.9, 0.0, None, None, 14.2, 147.8, 0.3, ...","[246.7, None, None]","[246.7, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
3,2020-03-15 21:15:00,1.584300e+12,67.103,0.0,0.0,67.103,0.0,0.0,0.0,"[0.1, 3.7, 0.0, None, None, 27.4, 92.3, 0.4, N...","[0.5, 0.9, 0.0, None, None, 12.1, 113.0, 0.3, ...","[244.5, None, None]","[244.5, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
4,2020-03-15 22:15:00,1.584303e+12,49.070,0.0,0.0,49.070,0.0,0.0,0.0,"[0.1, 3.7, 0.0, None, None, 27.3, 91.4, 0.4, N...","[0.5, 0.9, 0.0, None, None, 12.6, 113.2, 0.3, ...","[243.8, None, None]","[243.8, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

In [440]:
#Feature Engineering of Time Series
#df_5min_new['datetime']=pd.to_datetime(df_5min_new['date'])
df_5min_new['date'] = df_5min_new['datetime'].dt.strftime('%Y-%m-%d')
df_5min_new['year'] = df_5min_new['datetime'].dt.year 
df_5min_new['dayOfYear'] = df_5min_new['datetime'].dt.dayofyear
df_5min_new['month'] = df_5min_new['datetime'].dt.month 
df_5min_new['monthName'] = pd.DatetimeIndex(df_5min_new['datetime']).month_name()
df_5min_new['week'] = df_5min_new['datetime'].dt.week
df_5min_new['day'] = df_5min_new['datetime'].dt.day
df_5min_new['dayName'] = pd.DatetimeIndex(df_5min_new['datetime']).day_name()
df_5min_new['hour'] = df_5min_new['datetime'].dt.hour
df_5min_new['minute'] = df_5min_new['datetime'].dt.minute
df_5min_new['dayOfWeek'] = df_5min_new['datetime'].dt.dayofweek
df_5min_new['weekend'] = df_5min_new['dayOfWeek'].apply(lambda x: 1 if x >= 5 else 0)
df_5min_new['time'] = df_5min_new['datetime'].dt.time 
df_5min_new['time_Str'] = df_5min_new['datetime'].dt.time.astype(str)   
df_5min_new['dayMonth'] = df_5min_new["datetime"].dt.strftime('%m-%d')
df_5min_new['hourMinute'] = df_5min_new["datetime"].dt.strftime('%H:%M')

bins = [0,4,8,12,16,20,24]
labels = ['Late Night', 'Early Morning','Morning','Noon','Eve','Night']
df_5min_new['session'] = pd.cut(df_5min_new['hour'], bins=bins, labels=labels, include_lowest=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.

Remove Duplicates

In [441]:
df_5min_new = df_5min_new[~df_5min_new['datetime'].duplicated(keep = 'first')]
df_5min_new.head()

,datetime,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics,date,year,dayOfYear,month,monthName,week,day,dayName,hour,minute,dayOfWeek,weekend,time,time_Str,dayMonth,hourMinute,session
0,2020-03-15 18:15:00,1.584289e+12,0.000,0.0,0.0,0.000,0.0,0.0,0.0,"[0.1, 3.7, 0.0, -81.6, -60.0, 30.2, -230.6, -0...","[0.5, 0.9, 0.0, 55.4, 132.4, 14.0, 137.5, 0.2,...","[244.5, None, None]","[244.5, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...",2020-03-15,2020,75,3,March,11,15,Sunday,18,15,6,1,18:15:00,18:15:00,03-15,18:15,Eve
1,2020-03-15 19:15:00,1.584292e+12,35.615,0.0,0.0,35.615,0.0,0.0,0.0,"[0.1, 20.3, 0.0, None, 0.0, 47.0, 237.2, 0.3, ...","[0.5, 1.9, 0.0, None, 0.1, 13.6, 155.9, 0.2, N...","[247.3, None, None]","[247.3, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...",2020-03-15,2020,75,3,March,11,15,Sunday,19,15,6,1,19:15:00,19:15:00,03-15,19:15,Eve
2,2020-03-15 20:15:00,1.584296e+12,49.976,0.0,0.0,49.976,0.0,0.0,0.0,"[0.1, 3.8, 0.0, None, None, 33.4, 117.8, 0.4, ...","[0.5, 0.9, 0.0, None, None, 14.2, 147.8, 0.3, ...","[246.7, None, None]","[246.7, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...",2020-03-15,2020,75,3,March,11,15,Sunday,20,15,6,1,20:15:00,20:15:00,03-15,20:15,Eve
3,2020-03-15 21:15:00,1.584300e+12,67.103,0.0,0.0,67.103,0.0,0.0,0.0,"[0.1, 3.7, 0.0, None, None, 27.4, 92.3, 0.4, N...","[0.5, 0.9, 0.0, None, None, 12.1, 113.0, 0.3, ...","[244.5, None, None]","[244.5, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...",2020-03-15,2020,75,3,March,11,15,Sunday,21,15,6,1,21:15:00,21:15:00,03-15,21:15,Night
4,2020-03-15 22:15:00,1.584303e+12,49.070,0.0,0.0,49.070,0.0,0.0,0.0,"[0.1, 3.7, 0.0, None, None, 27.3, 91.4, 0.4, N...","[0.5, 0.9, 0.0, None, None, 12.6, 113.2, 0.3, ...","[243.8, None, None]","[243.8, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...",2020-03-15,2020,75,3,March,11,15,Sunday,22,15,6,1,22:15:00,22:15:00,03-15,22:15,Night

In [442]:
df_5min_new.columns

Index(['datetime', 'timestamp', 'consumption', 'solar', 'alwaysOn',
       'gridImport', 'gridExport', 'selfConsumption', 'selfSufficiency',
       'active', 'reactive', 'voltages', 'phaseVoltages', 'currentHarmonics',
       'voltageHarmonics', 'date', 'year', 'dayOfYear', 'month', 'monthName',
       'week', 'day', 'dayName', 'hour', 'minute', 'dayOfWeek', 'weekend',
       'time', 'time_Str', 'dayMonth', 'hourMinute', 'session'],
      dtype='object')

In [443]:
#Reorder columns
# Put non-ML friendly columns first - they may get dropped when loading into models
col_order = ['datetime', 'consumption', 'date', 'year', 'dayMonth', 'time', 'time_Str', 'hourMinute', 'session', 'monthName', 'dayName', 
             'dayOfYear', 'week', 'month', 'day', 'hour', 'minute', 'dayOfWeek', 'weekend', 'workingDay']
df_5min_new =df_5min_new.reindex(columns=col_order)

Data Inputation

In [444]:
#Investigate where missing row/hours are
# Consumption null values occur in continuous period 
# Do not use simple forward fill, impute average day profile for both days
df_5min_new[df_5min_new['consumption'].isnull()]

,datetime,consumption,date,year,dayMonth,time,time_Str,hourMinute,session,monthName,dayName,dayOfYear,week,month,day,hour,minute,dayOfWeek,weekend,workingDay
179,2020-03-23 05:15:00,NaN,2020-03-23,2020,03-23,05:15:00,05:15:00,05:15,Early Morning,March,Monday,83,13,3,23,5,15,0,0,NaN
600,2020-04-09 18:15:00,NaN,2020-04-09,2020,04-09,18:15:00,18:15:00,18:15,Eve,April,Thursday,100,15,4,9,18,15,3,0,NaN
1579,2020-05-20 13:15:00,NaN,2020-05-20,2020,05-20,13:15:00,13:15:00,13:15,Noon,May,Wednesday,141,21,5,20,13,15,2,0,NaN
1632,2020-05-22 18:15:00,NaN,2020-05-22,2020,05-22,18:15:00,18:15:00,18:15,Eve,May,Friday,143,21,5,22,18,15,4,0,NaN
1633,2020-05-22 19:15:00,NaN,2020-05-22,2020,05-22,19:15:00,19:15:00,19:15,Eve,May,Friday,143,21,5,22,19,15,4,0,NaN
1634,2020-05-22 20:15:00,NaN,2020-05-22,2020,05-22,20:15:00,20:15:00,20:15,Eve,May,Friday,143,21,5,22,20,15,4,0,NaN
1635,2020-05-22 21:15:00,NaN,2020-05-22,2020,05-22,21:15:00,21:15:00,21:15,Night,May,Friday,143,21,5,22,21,15,4,0,NaN
1636,2020-05-22 22:15:00,NaN,2020-05-22,2020,05-22,22:15:00,22:15:00,22:15,Night,May,Friday,143,21,5,22,22,15,4,0,NaN
1637,2020-05-22 23:15:00,NaN,2020-05-22,2020,05-22,23:15:00,23:15:00,23:15,Night,May,Friday,143,21,5,22,23,15,4,0,NaN
1638,2020-05-23 00:15:00,NaN,2020-05-23,2020,05-23,00:15:00,00:15:00,00:15,Late Night,May,Saturday,144,21,5,23,0,15,5,1,NaN
1639,2020-05-23 01:15:00,NaN,2020-05-23,2020,05-23,01:15:00,01:15:00,01:15,Late Night,May,Saturday,144,21,5,23,1,15,5,1,NaN
1640,2020-05-23 02:15:00,NaN,2020-05-23,2020,05-23,02:15:00,02:15:00,02:15,Late Night,May,Saturday,144,21,5,23,2,15,5,1,NaN
1641,2020-05-23 03:15:00,NaN,2020-05-23,2020,05-23,03:15:00,03:15:00,03:15,Late Night,May,Saturday,144,21,5,23,3,15,5,1,NaN
1642,2020-05-23 04:15:00,NaN,2020-05-23,2020,05-23,04:15:00,04:15:00,04:15,Late Night,May,Saturday,144,21,5,23,4,15,5,1,NaN
1643,2020-05-23 05:15:00,NaN,2020-05-23,2020,05-23,05:15:00,05:15:00,05:15,Early Morning,May,Saturday,144,21,5,23,5,15,5,1,NaN
1644,2020-05-23 06:15:00,NaN,2020-05-23,2020,05-23,06:15:00,06:15:00,06:15,Early Morning,May,Saturday,144,21,5,23,6,15,5,1,NaN
1645,2020-05-23 07:15:00,NaN,2020-05-23,2020,05-23,07:15:00,07:15:00,07:15,Early Morning,May,Saturday,144,21,5,23,7,15,5,1,NaN
1646,2020-05-23 08:15:00,NaN,2020-05-23,2020,05-23,08:15:00,08:15:00,08:15,Early Morning,May,Saturday,144,21,5,23,8,15,5,1,NaN
1647,2020-05-23 09:15:00,NaN,2020-05-23,2020,05-23,09:15:00,09:15:00,09:15,Morning,May,Saturday,144,21,5,23,9,15,5,1,NaN
1648,2020-05-23 10:15:00,NaN,2020-05-23,2020,05-23,10:15:00,10:15:00,10:15,Morning,May,Saturday,144,21,5,23,10,15,5,1,NaN
1649,2020-05-23 11:15:00,NaN,2020-05-23,2020,05-23,11:15:00,11:15:00,11:15,Morning,May,Saturday,144,21,5,23,11,15,5,1,NaN
1650,2020-05-23 12:15:00,NaN,2020-05-23,2020,05-23,12:15:00,12:15:00,12:15,Morning,May,Saturday,144,21,5,23,12,15,5,1,NaN
1651,2020-05-23 13:15:00,NaN,2020-05-23,2020,05-23,13:15:00,13:15:00,13:15,Noon,May,Saturday,144,21,5,23,13,15,5,1,NaN
1652,2020-05-23 14:15:00,NaN,2020-05-23,2020,05-23,14:15:00,14:15:00,14:15,Noon,May,Saturday,144,21,5,23,14,15,5,1,NaN
2375,2020-06-22 17:15:00,NaN,2020-06-22,2020,06-22,17:15:00,17:15:00,17:15,Eve,June,Monday,174,26,6,22,17,15,0,0,NaN
5400,2020-10-26 18:15:00,NaN,2020-10-26,2020,10-26,18:15:00,18:15:00,18:15,Eve,October,Monday,300,44,10,26,18,15,0,0,NaN
6974,2020-12-31 08:15:00,NaN,2020-12-31,2020,12-31,08:15:00,08:15:00,08:15,Early Morning,December,Thursday,366,53,12,31,8,15,3,0,NaN
7583,2021-01-25 17:15:00,NaN,2021-01-25,2021,01-25,17:15:00,17:15:00,17:15,Eve,January,Monday,25,4,1,25,17,15,0,0,NaN

In [445]:
#df_5min_new[df_5min_new['datetime']=='2020-03-23 05:15:00'].mask(df_5min_new['consumption']=='NaN').ffill(downcast='infer')

In [446]:

# Check out missing period
#df_5min_new[(df_5min_new['datetime']>='2020-03-23 00:00:00') & 
#       (df_5min_new['datetime']<='2021-01-25 00:00:00')]['consumption'].plot()

In [447]:
#imputing into march 
# Use simple forward fill to replace negative cloud cover values
#df_5min_new['consumption']=df_5min_new['consumption'].mask(df_5min_new['consumption'].isnull()).ffill(downcast='infer')

In [353]:
# Get average Weekday and Weekend profiles for May and impute profile
# create_monthly_profiles(df, column)
#profile_df_5min = create_monthly_profiles(df_5min_new, 'consumption')
#profile_df_5min

1 hour data wrangling

In [448]:
asset ="/content/drive/MyDrive/NEEDENERGY/data_hourly_id_47803.csv"

In [449]:
df_hourly = load_data(asset)

In [450]:
df_hourly.head()

,date,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-15 18:00:00,1584288000000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,"[1.3, 78.9, -45.1, -297.3, -163.6, 321.1, 143....","[6.2, 38.9, 15.3, 534.8, 1134.3, 151.0, 1309.9...","[245.8, None, None]","[245.8, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-03-15 19:00:00,1584291600000,913.000,0.0,0.0,913.000,0.0,0.0,0.0,"[1.2, 596.1, -509.8, 72.6, 0.0, 907.0, 2273.7,...","[6.0, 343.5, 228.7, 262.0, 0.2, 439.9, 2077.9,...","[245.6, None, None]","[245.6, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,2020-03-15 20:00:00,1584295200000,623.471,0.0,0.0,623.471,0.0,0.0,0.0,"[1.5, 44.8, 0.0, None, None, 387.2, 1148.0, 6....","[7.4, 10.8, 0.0, None, None, 155.4, 1374.2, 3....","[244.9, None, None]","[244.9, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
3,2020-03-15 21:00:00,1584298800000,765.984,0.0,0.0,765.984,0.0,0.0,0.0,"[1.2, 44.4, 0.0, None, None, 332.9, 1118.7, 4....","[6.0, 10.8, 0.0, None, None, 145.8, 1314.5, 2....","[244.4, None, None]","[244.4, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
4,2020-03-15 22:00:00,1584302400000,585.041,0.0,0.0,585.041,0.0,0.0,0.0,"[1.5, 44.4, 0.0, None, None, 329.0, 1414.6, 5....","[7.5, 10.8, 0.0, None, None, 155.1, 1395.1, 3....","[244.8, None, None]","[244.8, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

In [451]:
#basic profiling
df_hourly.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7979 entries, 0 to 7978
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              7979 non-null   datetime64[ns]
 1   timestamp         7979 non-null   int64
 2   consumption       7979 non-null   float64
 3   solar             7979 non-null   float64
 4   alwaysOn          7979 non-null   float64
 5   gridImport        7979 non-null   float64
 6   gridExport        7979 non-null   float64
 7   selfConsumption   7979 non-null   float64
 8   selfSufficiency   7979 non-null   float64
 9   active            7979 non-null   object
 10  reactive          7979 non-null   object
 11  voltages          7979 non-null   object
 12  phaseVoltages     7979 non-null   object
 13  currentHarmonics  7979 non-null   object
 14  voltageHarmonics  7979 non-null   object
dtypes: datetime64[ns](1), float64(7), int64(1), object(6)
memory usage: 997.4+ KB

In [452]:
#statistcal summary
df_hourly.describe

<bound method NDFrame.describe of                     date      timestamp  consumption    solar  alwaysOn  \
0    2020-03-15 18:00:00  1584288000000        0.000    0.000     0.000
1    2020-03-15 19:00:00  1584291600000      913.000    0.000     0.000
2    2020-03-15 20:00:00  1584295200000      623.471    0.000     0.000
3    2020-03-15 21:00:00  1584298800000      765.984    0.000     0.000
4    2020-03-15 22:00:00  1584302400000      585.041    0.000     0.000
...                  ...            ...          ...      ...       ...
7974 2021-02-11 21:00:00  1613070000000     1973.376  572.885  1006.751
7975 2021-02-11 22:00:00  1613073600000     1995.612  576.278  1006.751
7976 2021-02-11 23:00:00  1613077200000     2020.629  564.869  1006.751
7977 2021-02-12 00:00:00  1613080800000     1960.142  556.150  1006.751
7978 2021-02-12 01:00:00  1613084400000     1970.954  555.986  1006.751

      gridImport  gridExport  selfConsumption  selfSufficiency  \
0          0.000         0.0              0.0             0.00
1        913.000         0.0              0.0             0.00
2        623.471         0.0              0.0             0.00
3        765.984         0.0              0.0             0.00
4        585.041         0.0              0.0             0.00
...          ...         ...              ...              ...
7974    1400.191         0.0            100.0            29.05
7975    1419.533         0.0            100.0            28.87
7976    1455.660         0.0            100.0            27.96
7977    1403.792         0.0            100.0            28.38
7978    1415.067         0.0            100.0            28.20

                                                 active  \
0     [1.3, 78.9, -45.1, -297.3, -163.6, 321.1, 143....
1     [1.2, 596.1, -509.8, 72.6, 0.0, 907.0, 2273.7,...
2     [1.5, 44.8, 0.0, None, None, 387.2, 1148.0, 6....
3     [1.2, 44.4, 0.0, None, None, 332.9, 1118.7, 4....
4     [1.5, 44.4, 0.0, None, None, 329.0, 1414.6, 5....
...                                                 ...
7974  [1.5, 43.5, -1.2, None, None, None, None, 5.9,...
7975  [1.2, 43.1, -1.2, None, None, None, None, 4.8,...
7976  [1.5, 42.9, -1.2, None, None, None, None, 5.9,...
7977  [1.2, 42.6, -1.2, None, None, None, None, 4.8,...
7978  [1.5, 42.9, -1.2, None, None, None, None, 5.9,...

                                               reactive             voltages  \
0     [6.2, 38.9, 15.3, 534.8, 1134.3, 151.0, 1309.9...  [245.8, None, None]
1     [6.0, 343.5, 228.7, 262.0, 0.2, 439.9, 2077.9,...  [245.6, None, None]
2     [7.4, 10.8, 0.0, None, None, 155.4, 1374.2, 3....  [244.9, None, None]
3     [6.0, 10.8, 0.0, None, None, 145.8, 1314.5, 2....  [244.4, None, None]
4     [7.5, 10.8, 0.0, None, None, 155.1, 1395.1, 3....  [244.8, None, None]
...                                                 ...                  ...
7974  [-6.6, 10.8, 0.0, None, None, None, None, -2.9...  [242.8, None, None]
7975  [-5.3, 10.1, 0.0, None, None, None, None, -2.4...  [241.6, None, None]
7976  [-6.3, 9.9, 0.0, None, None, None, None, -2.8,...  [240.7, None, None]
7977  [-4.8, 9.7, 0.0, None, None, None, None, -2.4,...  [239.7, None, None]
7978  [-6.2, 10.0, 0.0, None, None, None, None, -2.8...  [240.6, None, None]

            phaseVoltages                                   currentHarmonics  \
0     [245.8, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
1     [245.6, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
2     [244.9, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
3     [244.4, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
4     [244.8, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
...                   ...                                                ...
7974  [242.8, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
7975  [241.6, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
7976  [240.7, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
7977  [239.7, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
7978  [240.6, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...

                                       voltageHarmonics
0     [[], [], [], [], [], [], [], [], [], [], [], [...
1     [[], [], [], [], [], [], [], [], [], [], [], [...
2     [[], [], [], [], [], [], [], [], [], [], [], [...
3     [[], [], [], [], [], [], [], [], [], [], [], [...
4     [[], [], [], [], [], [], [], [], [], [], [], [...
...                                                 ...
7974  [[], [], [], [], [], [], [], [], [], [], [], [...
7975  [[], [], [], [], [], [], [], [], [], [], [], [...
7976  [[], [], [], [], [], [], [], [], [], [], [], [...
7977  [[], [], [], [], [], [], [], [], [], [], [], [...
7978  [[], [], [], [], [], [], [], [], [], [], [], [...

[7979 rows x 15 columns]>

In [453]:
#List of features
df_hourly.columns

Index(['date', 'timestamp', 'consumption', 'solar', 'alwaysOn', 'gridImport',
       'gridExport', 'selfConsumption', 'selfSufficiency', 'active',
       'reactive', 'voltages', 'phaseVoltages', 'currentHarmonics',
       'voltageHarmonics'],
      dtype='object')

In [454]:
df_hourly_new = df_hourly.copy()

df_hourly_new.head()

,date,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-15 18:00:00,1584288000000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,"[1.3, 78.9, -45.1, -297.3, -163.6, 321.1, 143....","[6.2, 38.9, 15.3, 534.8, 1134.3, 151.0, 1309.9...","[245.8, None, None]","[245.8, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-03-15 19:00:00,1584291600000,913.000,0.0,0.0,913.000,0.0,0.0,0.0,"[1.2, 596.1, -509.8, 72.6, 0.0, 907.0, 2273.7,...","[6.0, 343.5, 228.7, 262.0, 0.2, 439.9, 2077.9,...","[245.6, None, None]","[245.6, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,2020-03-15 20:00:00,1584295200000,623.471,0.0,0.0,623.471,0.0,0.0,0.0,"[1.5, 44.8, 0.0, None, None, 387.2, 1148.0, 6....","[7.4, 10.8, 0.0, None, None, 155.4, 1374.2, 3....","[244.9, None, None]","[244.9, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
3,2020-03-15 21:00:00,1584298800000,765.984,0.0,0.0,765.984,0.0,0.0,0.0,"[1.2, 44.4, 0.0, None, None, 332.9, 1118.7, 4....","[6.0, 10.8, 0.0, None, None, 145.8, 1314.5, 2....","[244.4, None, None]","[244.4, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
4,2020-03-15 22:00:00,1584302400000,585.041,0.0,0.0,585.041,0.0,0.0,0.0,"[1.5, 44.4, 0.0, None, None, 329.0, 1414.6, 5....","[7.5, 10.8, 0.0, None, None, 155.1, 1395.1, 3....","[244.8, None, None]","[244.8, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

In [455]:
#Check for duplicates
df_hourly_new.index[df_hourly_new['date'].duplicated(keep=False)==True]

Int64Index([], dtype='int64')

In [456]:
# Check for missing info using Missingno Package
msno = import_package('missingno')
msno.matrix(df_hourly_new)

missingno Version: 0.4.2

In [457]:
# Check if there are any periods of zero values
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
features = df_hourly_new.select_dtypes(include=numerics).columns 
for feature in features: 
    zero_results = df_hourly_new[df_hourly_new[feature]==0]
zero_results.head()

,date,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-15 18:00:00,1584288000000,0.000,0.0,0.0,0.000,0.0,0.0,0.0,"[1.3, 78.9, -45.1, -297.3, -163.6, 321.1, 143....","[6.2, 38.9, 15.3, 534.8, 1134.3, 151.0, 1309.9...","[245.8, None, None]","[245.8, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-03-15 19:00:00,1584291600000,913.000,0.0,0.0,913.000,0.0,0.0,0.0,"[1.2, 596.1, -509.8, 72.6, 0.0, 907.0, 2273.7,...","[6.0, 343.5, 228.7, 262.0, 0.2, 439.9, 2077.9,...","[245.6, None, None]","[245.6, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,2020-03-15 20:00:00,1584295200000,623.471,0.0,0.0,623.471,0.0,0.0,0.0,"[1.5, 44.8, 0.0, None, None, 387.2, 1148.0, 6....","[7.4, 10.8, 0.0, None, None, 155.4, 1374.2, 3....","[244.9, None, None]","[244.9, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
3,2020-03-15 21:00:00,1584298800000,765.984,0.0,0.0,765.984,0.0,0.0,0.0,"[1.2, 44.4, 0.0, None, None, 332.9, 1118.7, 4....","[6.0, 10.8, 0.0, None, None, 145.8, 1314.5, 2....","[244.4, None, None]","[244.4, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
4,2020-03-15 22:00:00,1584302400000,585.041,0.0,0.0,585.041,0.0,0.0,0.0,"[1.5, 44.4, 0.0, None, None, 329.0, 1414.6, 5....","[7.5, 10.8, 0.0, None, None, 155.1, 1395.1, 3....","[244.8, None, None]","[244.8, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

In [458]:
# Check for any missing time steps, create hourly datetime index and compare to length of dataframe
start = df_hourly_new['date'].min()
end = df_hourly_new['date'].max()
full_index = pd.date_range(start, end, freq='H')
len(full_index) == len(df_hourly_new)

False

In [459]:
df_hourly_new.set_index('date', inplace = True)
df_hourly_new = df_hourly_new.reindex(full_index)
df_hourly_new.index

DatetimeIndex(['2020-03-15 18:00:00', '2020-03-15 19:00:00',
               '2020-03-15 20:00:00', '2020-03-15 21:00:00',
               '2020-03-15 22:00:00', '2020-03-15 23:00:00',
               '2020-03-16 00:00:00', '2020-03-16 01:00:00',
               '2020-03-16 02:00:00', '2020-03-16 03:00:00',
               ...
               '2021-02-11 16:00:00', '2021-02-11 17:00:00',
               '2021-02-11 18:00:00', '2021-02-11 19:00:00',
               '2021-02-11 20:00:00', '2021-02-11 21:00:00',
               '2021-02-11 22:00:00', '2021-02-11 23:00:00',
               '2021-02-12 00:00:00', '2021-02-12 01:00:00'],
              dtype='datetime64[ns]', length=8000, freq='H')

In [460]:
#Have a look at missing values
print(f"{df_hourly_new.isnull().sum()}\n\n")
print(f"Percentage of missing values:\t{(df_hourly_new['consumption'].isnull().sum()/df_hourly_new['timestamp'].count())*100}")

timestamp           21
consumption         21
solar               21
alwaysOn            21
gridImport          21
gridExport          21
selfConsumption     21
selfSufficiency     21
active              21
reactive            21
voltages            21
phaseVoltages       21
currentHarmonics    21
voltageHarmonics    21
dtype: int64


Percentage of missing values:	0.26319087604963026

In [461]:

df_hourly_new.reset_index(inplace=True)
df_hourly_new.rename(columns = {'index':'datetime'}, inplace = True)
df_hourly_new.head()

,datetime,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-15 18:00:00,1.584288e+12,0.000,0.0,0.0,0.000,0.0,0.0,0.0,"[1.3, 78.9, -45.1, -297.3, -163.6, 321.1, 143....","[6.2, 38.9, 15.3, 534.8, 1134.3, 151.0, 1309.9...","[245.8, None, None]","[245.8, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-03-15 19:00:00,1.584292e+12,913.000,0.0,0.0,913.000,0.0,0.0,0.0,"[1.2, 596.1, -509.8, 72.6, 0.0, 907.0, 2273.7,...","[6.0, 343.5, 228.7, 262.0, 0.2, 439.9, 2077.9,...","[245.6, None, None]","[245.6, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,2020-03-15 20:00:00,1.584295e+12,623.471,0.0,0.0,623.471,0.0,0.0,0.0,"[1.5, 44.8, 0.0, None, None, 387.2, 1148.0, 6....","[7.4, 10.8, 0.0, None, None, 155.4, 1374.2, 3....","[244.9, None, None]","[244.9, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
3,2020-03-15 21:00:00,1.584299e+12,765.984,0.0,0.0,765.984,0.0,0.0,0.0,"[1.2, 44.4, 0.0, None, None, 332.9, 1118.7, 4....","[6.0, 10.8, 0.0, None, None, 145.8, 1314.5, 2....","[244.4, None, None]","[244.4, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
4,2020-03-15 22:00:00,1.584302e+12,585.041,0.0,0.0,585.041,0.0,0.0,0.0,"[1.5, 44.4, 0.0, None, None, 329.0, 1414.6, 5....","[7.5, 10.8, 0.0, None, None, 155.1, 1395.1, 3....","[244.8, None, None]","[244.8, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

In [462]:
#Feature Engineering of Time Series
df_hourly_new['date'] = df_hourly_new['datetime'].dt.strftime('%Y-%m-%d')
df_hourly_new['year'] = df_hourly_new['datetime'].dt.year 
df_hourly_new['dayOfYear'] = df_hourly_new['datetime'].dt.dayofyear
df_hourly_new['month'] = df_hourly_new['datetime'].dt.month 
df_hourly_new['monthName'] = pd.DatetimeIndex(df_hourly_new['datetime']).month_name()
df_hourly_new['week'] = df_hourly_new['datetime'].dt.week
df_hourly_new['day'] = df_hourly_new['datetime'].dt.day
df_hourly_new['dayName'] = pd.DatetimeIndex(df_hourly_new['datetime']).day_name()
df_hourly_new['hour'] = df_hourly_new['datetime'].dt.hour
df_hourly_new['minute'] = df_hourly_new['datetime'].dt.minute
df_hourly_new['dayOfWeek'] = df_hourly_new['datetime'].dt.dayofweek
df_hourly_new['weekend'] = df_hourly_new['dayOfWeek'].apply(lambda x: 1 if x >= 5 else 0)
df_hourly_new['time'] = df_hourly_new['datetime'].dt.time 
df_hourly_new['time_Str'] = df_hourly_new['datetime'].dt.time.astype(str)   
df_hourly_new['dayMonth'] = df_hourly_new["datetime"].dt.strftime('%m-%d')
df_hourly_new['hourMinute'] = df_hourly_new["datetime"].dt.strftime('%H:%M')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  import sys

In [463]:
bins = [0,4,8,12,16,20,24]
labels = ['Late Night', 'Early Morning','Morning','Noon','Eve','Night']
df_hourly_new['session'] = pd.cut(df_hourly_new['hour'], bins=bins, labels=labels, include_lowest=True)

In [464]:
df_hourly_new = df_hourly_new[~df_hourly_new['datetime'].duplicated(keep = 'first')]
df_hourly_new.head()

,datetime,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics,date,year,dayOfYear,month,monthName,week,day,dayName,hour,minute,dayOfWeek,weekend,time,time_Str,dayMonth,hourMinute,session
0,2020-03-15 18:00:00,1.584288e+12,0.000,0.0,0.0,0.000,0.0,0.0,0.0,"[1.3, 78.9, -45.1, -297.3, -163.6, 321.1, 143....","[6.2, 38.9, 15.3, 534.8, 1134.3, 151.0, 1309.9...","[245.8, None, None]","[245.8, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...",2020-03-15,2020,75,3,March,11,15,Sunday,18,0,6,1,18:00:00,18:00:00,03-15,18:00,Eve
1,2020-03-15 19:00:00,1.584292e+12,913.000,0.0,0.0,913.000,0.0,0.0,0.0,"[1.2, 596.1, -509.8, 72.6, 0.0, 907.0, 2273.7,...","[6.0, 343.5, 228.7, 262.0, 0.2, 439.9, 2077.9,...","[245.6, None, None]","[245.6, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...",2020-03-15,2020,75,3,March,11,15,Sunday,19,0,6,1,19:00:00,19:00:00,03-15,19:00,Eve
2,2020-03-15 20:00:00,1.584295e+12,623.471,0.0,0.0,623.471,0.0,0.0,0.0,"[1.5, 44.8, 0.0, None, None, 387.2, 1148.0, 6....","[7.4, 10.8, 0.0, None, None, 155.4, 1374.2, 3....","[244.9, None, None]","[244.9, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...",2020-03-15,2020,75,3,March,11,15,Sunday,20,0,6,1,20:00:00,20:00:00,03-15,20:00,Eve
3,2020-03-15 21:00:00,1.584299e+12,765.984,0.0,0.0,765.984,0.0,0.0,0.0,"[1.2, 44.4, 0.0, None, None, 332.9, 1118.7, 4....","[6.0, 10.8, 0.0, None, None, 145.8, 1314.5, 2....","[244.4, None, None]","[244.4, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...",2020-03-15,2020,75,3,March,11,15,Sunday,21,0,6,1,21:00:00,21:00:00,03-15,21:00,Night
4,2020-03-15 22:00:00,1.584302e+12,585.041,0.0,0.0,585.041,0.0,0.0,0.0,"[1.5, 44.4, 0.0, None, None, 329.0, 1414.6, 5....","[7.5, 10.8, 0.0, None, None, 155.1, 1395.1, 3....","[244.8, None, None]","[244.8, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...",2020-03-15,2020,75,3,March,11,15,Sunday,22,0,6,1,22:00:00,22:00:00,03-15,22:00,Night

In [465]:
df_hourly_new.columns

Index(['datetime', 'timestamp', 'consumption', 'solar', 'alwaysOn',
       'gridImport', 'gridExport', 'selfConsumption', 'selfSufficiency',
       'active', 'reactive', 'voltages', 'phaseVoltages', 'currentHarmonics',
       'voltageHarmonics', 'date', 'year', 'dayOfYear', 'month', 'monthName',
       'week', 'day', 'dayName', 'hour', 'minute', 'dayOfWeek', 'weekend',
       'time', 'time_Str', 'dayMonth', 'hourMinute', 'session'],
      dtype='object')

In [466]:
#Reorder columns
# Put non-ML friendly columns first - they may get dropped when loading into models
col_order = ['datetime', 'consumption', 'date', 'year', 'dayMonth', 'time', 'time_Str', 'hourMinute', 'session', 'monthName', 'dayName', 
             'dayOfYear', 'week', 'month', 'day', 'hour', 'minute', 'dayOfWeek', 'weekend', 'workingDay']
df_hourly_new =df_hourly_new.reindex(columns=col_order)

In [467]:
#df_hourly_new1=df_hourly_new.copy()

Data Inputation for Hourly Dataset

In [468]:

# impute average day profile for both days
#df_hourly_new1[df_hourly_new1['year']==2020] [df_hourly_new1['consumption'].isnull()]['month'].unique()

In [469]:
#mask = (df_hourly_new1['datetime'] > '2020-03-15 00:00:00') & (df_hourly_new1['datetime'] <= '2000-6-10')
#print(df.loc[mask])

In [470]:

#Check out missing period
#df_hourly_new1[(df_5min_new['datetime']>='2020-03-15 00:00:00') & 
#       (df_hourly_new1['datetime']<='2021-02-12 00:00:00')]['consumption'].plot()

NeedEnergyAPI_daily Wrangling

In [471]:
asset = "/content/drive/MyDrive/NEEDENERGY/data_daily_id_47803.csv"

In [472]:
df_daily = load_data(asset)

In [473]:
#df_daily.head()

In [474]:
#basic profiling
df_daily.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 335 entries, 0 to 334
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              335 non-null    datetime64[ns]
 1   timestamp         335 non-null    int64
 2   consumption       335 non-null    float64
 3   solar             335 non-null    float64
 4   alwaysOn          335 non-null    float64
 5   gridImport        335 non-null    float64
 6   gridExport        335 non-null    float64
 7   selfConsumption   335 non-null    float64
 8   selfSufficiency   335 non-null    float64
 9   active            335 non-null    object
 10  reactive          335 non-null    object
 11  voltages          335 non-null    object
 12  phaseVoltages     335 non-null    object
 13  currentHarmonics  335 non-null    object
 14  voltageHarmonics  335 non-null    object
dtypes: datetime64[ns](1), float64(7), int64(1), object(6)
memory usage: 41.9+ KB

In [475]:
#statistcal summary
df_daily.describe

<bound method NDFrame.describe of           date      timestamp  consumption      solar   alwaysOn  gridImport  \
0   2020-03-15  1584223200000     3482.000      0.000      0.000    3482.000
1   2020-03-16  1584309600000    15769.626      0.000      0.000   15769.626
2   2020-03-17  1584396000000    19615.313      0.000   3930.300   19615.313
3   2020-03-18  1584482400000    68889.900  22628.600   7605.922   46261.000
4   2020-03-19  1584568800000    86955.199  29753.017  50113.192   57200.482
..         ...            ...          ...        ...        ...         ...
330 2021-02-08  1612735200000    91610.001  18719.391  32846.033   72890.009
331 2021-02-09  1612821600000    77847.752  18578.084  24079.251   59269.767
332 2021-02-10  1612908000000    78438.223  18758.780  23995.351   59679.743
333 2021-02-11  1612994400000    77076.570  17278.908  24163.151   59797.662
334 2021-02-12  1613080800000    73599.842  14890.850  25901.851   58709.092

     gridExport  selfConsumption  selfSufficiency  \
0           0.0              0.0             0.00
1           0.0              0.0             0.00
2           0.0              0.0             0.00
3           0.0            100.0            32.85
4           0.0            100.0            34.22
..          ...              ...              ...
330         0.0            100.0            20.43
331         0.0            100.0            23.86
332         0.0            100.0            23.91
333         0.0            100.0            22.42
334         0.0            100.0            20.23

                                                active  \
0    [7.9, 853.1, -554.9, -224.7, -163.6, 2674.0, 8...
1    [33.1, 1048.4, 0.0, None, None, 15025.2, 56670...
2    [32.7, 952.5, 0.0, None, None, 15279.5, 52163....
3    [32.4, 947.6, 0.0, None, None, 5019.4, 19214.0...
4    [32.8, 1039.4, 0.0, None, None, None, None, 11...
..                                                 ...
330  [33.0, 1029.0, -0.4, None, None, None, None, 1...
331  [32.7, 1046.1, -3.2, None, None, None, None, 1...
332  [32.4, 1024.5, -0.3, None, None, None, None, 1...
333  [32.6, 1039.6, -6.3, None, None, None, None, 1...
334  [31.1, 989.6, -12.9, None, None, None, None, 1...

                                              reactive             voltages  \
0    [39.1, 425.6, 244.0, 796.8, 1134.5, 1219.7, 91...  [245.3, None, None]
1    [154.4, 247.2, 0.3, None, None, 6569.6, 39446....  [244.9, None, None]
2    [137.9, 207.4, 0.0, None, None, 7038.1, 38825....  [234.3, None, None]
3    [133.8, 204.8, 0.0, None, None, 2223.5, 14859....  [232.1, None, None]
4    [149.8, 240.3, 0.5, None, None, None, None, 68...  [242.5, None, None]
..                                                 ...                  ...
330  [-142.0, 247.2, 0.0, None, None, None, None, -...  [240.4, None, None]
331  [-148.9, 253.7, 0.0, None, None, None, None, -...  [245.7, None, None]
332  [-135.1, 243.7, 0.0, None, None, None, None, -...  [240.5, None, None]
333  [-139.5, 252.2, 0.0, None, None, None, None, -...  [241.0, None, None]
334  [-127.5, 233.1, 0.0, None, None, None, None, -...  [240.0, None, None]

           phaseVoltages                                   currentHarmonics  \
0    [245.3, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
1    [244.9, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
2    [234.3, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
3    [232.1, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
4    [242.5, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
..                   ...                                                ...
330  [240.4, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
331  [245.7, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
332  [240.5, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
333  [241.0, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
334  [240.0, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...

                                      voltageHarmonics
0    [[], [], [], [], [], [], [], [], [], [], [], [...
1    [[], [], [], [], [], [], [], [], [], [], [], [...
2    [[], [], [], [], [], [], [], [], [], [], [], [...
3    [[], [], [], [], [], [], [], [], [], [], [], [...
4    [[], [], [], [], [], [], [], [], [], [], [], [...
..                                                 ...
330  [[], [], [], [], [], [], [], [], [], [], [], [...
331  [[], [], [], [], [], [], [], [], [], [], [], [...
332  [[], [], [], [], [], [], [], [], [], [], [], [...
333  [[], [], [], [], [], [], [], [], [], [], [], [...
334  [[], [], [], [], [], [], [], [], [], [], [], [...

[335 rows x 15 columns]>

In [476]:
df_daily_new = df_daily.copy()

In [477]:
df_daily_new.head()

,date,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-15,1584223200000,3482.000,0.000,0.000,3482.000,0.0,0.0,0.00,"[7.9, 853.1, -554.9, -224.7, -163.6, 2674.0, 8...","[39.1, 425.6, 244.0, 796.8, 1134.5, 1219.7, 91...","[245.3, None, None]","[245.3, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-03-16,1584309600000,15769.626,0.000,0.000,15769.626,0.0,0.0,0.00,"[33.1, 1048.4, 0.0, None, None, 15025.2, 56670...","[154.4, 247.2, 0.3, None, None, 6569.6, 39446....","[244.9, None, None]","[244.9, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,2020-03-17,1584396000000,19615.313,0.000,3930.300,19615.313,0.0,0.0,0.00,"[32.7, 952.5, 0.0, None, None, 15279.5, 52163....","[137.9, 207.4, 0.0, None, None, 7038.1, 38825....","[234.3, None, None]","[234.3, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
3,2020-03-18,1584482400000,68889.900,22628.600,7605.922,46261.000,0.0,100.0,32.85,"[32.4, 947.6, 0.0, None, None, 5019.4, 19214.0...","[133.8, 204.8, 0.0, None, None, 2223.5, 14859....","[232.1, None, None]","[232.1, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
4,2020-03-19,1584568800000,86955.199,29753.017,50113.192,57200.482,0.0,100.0,34.22,"[32.8, 1039.4, 0.0, None, None, None, None, 11...","[149.8, 240.3, 0.5, None, None, None, None, 68...","[242.5, None, None]","[242.5, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

In [478]:
#Check for duplicates
df_daily_new.index[df_daily_new['date'].duplicated(keep=False)==True]

Int64Index([], dtype='int64')

In [479]:
# Check for missing info using Missingno Package
msno = import_package('missingno')
msno.matrix(df_daily_new)

missingno Version: 0.4.2

In [480]:
# Check if there are any periods of zero values
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
features = df_daily_new.select_dtypes(include=numerics).columns 
for feature in features: 
    zero_results = df_daily_new[df_daily_new[feature]==0]
zero_results.head()

,date,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-15,1584223200000,3482.000,0.0,0.0,3482.000,0.0,0.0,0.0,"[7.9, 853.1, -554.9, -224.7, -163.6, 2674.0, 8...","[39.1, 425.6, 244.0, 796.8, 1134.5, 1219.7, 91...","[245.3, None, None]","[245.3, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-03-16,1584309600000,15769.626,0.0,0.0,15769.626,0.0,0.0,0.0,"[33.1, 1048.4, 0.0, None, None, 15025.2, 56670...","[154.4, 247.2, 0.3, None, None, 6569.6, 39446....","[244.9, None, None]","[244.9, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,2020-03-17,1584396000000,19615.313,0.0,3930.3,19615.313,0.0,0.0,0.0,"[32.7, 952.5, 0.0, None, None, 15279.5, 52163....","[137.9, 207.4, 0.0, None, None, 7038.1, 38825....","[234.3, None, None]","[234.3, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

In [481]:
# Check for any missing time steps, create hourly datetime index and compare to length of dataframe
start = df_daily_new['date'].min()
end = df_daily_new['date'].max()
full_index = pd.date_range(start, end, freq='H')
len(full_index) == len(df_daily_new)

False

In [482]:

df_daily_new.set_index('date', inplace = True)
df_daily_new = df_daily_new.reindex(full_index)
df_daily_new.index

DatetimeIndex(['2020-03-15 00:00:00', '2020-03-15 01:00:00',
               '2020-03-15 02:00:00', '2020-03-15 03:00:00',
               '2020-03-15 04:00:00', '2020-03-15 05:00:00',
               '2020-03-15 06:00:00', '2020-03-15 07:00:00',
               '2020-03-15 08:00:00', '2020-03-15 09:00:00',
               ...
               '2021-02-11 15:00:00', '2021-02-11 16:00:00',
               '2021-02-11 17:00:00', '2021-02-11 18:00:00',
               '2021-02-11 19:00:00', '2021-02-11 20:00:00',
               '2021-02-11 21:00:00', '2021-02-11 22:00:00',
               '2021-02-11 23:00:00', '2021-02-12 00:00:00'],
              dtype='datetime64[ns]', length=8017, freq='H')

In [483]:
#Have a look at missing values
print(f"{df_daily_new.isnull().sum()}\n\n")
print(f"Percentage of missing values:\t{(df_daily_new['consumption'].isnull().sum()/df_daily_new['timestamp'].count())*100}")

timestamp           7682
consumption         7682
solar               7682
alwaysOn            7682
gridImport          7682
gridExport          7682
selfConsumption     7682
selfSufficiency     7682
active              7682
reactive            7682
voltages            7682
phaseVoltages       7682
currentHarmonics    7682
voltageHarmonics    7682
dtype: int64


Percentage of missing values:	2293.134328358209

In [484]:
df_daily_new.reset_index(inplace=True)
df_daily_new.rename(columns = {'index':'datetime'}, inplace = True)
df_daily_new.head()

,datetime,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-15 00:00:00,1.584223e+12,3482.0,0.0,0.0,3482.0,0.0,0.0,0.0,"[7.9, 853.1, -554.9, -224.7, -163.6, 2674.0, 8...","[39.1, 425.6, 244.0, 796.8, 1134.5, 1219.7, 91...","[245.3, None, None]","[245.3, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-03-15 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-03-15 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-03-15 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-03-15 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [485]:
#Feature Engineering of Time Series
#df_5min_new['datetime']=pd.to_datetime(df_5min_new['date'])
df_daily_new['date'] = df_daily_new['datetime'].dt.strftime('%Y-%m-%d')
df_daily_new['year'] = df_daily_new['datetime'].dt.year 
df_daily_new['dayOfYear'] = df_daily_new['datetime'].dt.dayofyear
df_daily_new['month'] = df_daily_new['datetime'].dt.month 
df_daily_new['monthName'] = pd.DatetimeIndex(df_daily_new['datetime']).month_name()
df_daily_new['week'] = df_daily_new['datetime'].dt.week
df_daily_new['day'] = df_daily_new['datetime'].dt.day
df_daily_new['dayName'] = pd.DatetimeIndex(df_daily_new['datetime']).day_name()
df_daily_new['hour'] = df_daily_new['datetime'].dt.hour
df_daily_new['minute'] = df_daily_new['datetime'].dt.minute
df_daily_new['dayOfWeek'] = df_daily_new['datetime'].dt.dayofweek
df_daily_new['weekend'] = df_daily_new['dayOfWeek'].apply(lambda x: 1 if x >= 5 else 0)
df_daily_new['time'] = df_daily_new['datetime'].dt.time 
df_daily_new['time_Str'] = df_daily_new['datetime'].dt.time.astype(str)   
df_daily_new['dayMonth'] = df_daily_new["datetime"].dt.strftime('%m-%d')
df_daily_new['hourMinute'] = df_daily_new["datetime"].dt.strftime('%H:%M')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.

In [486]:
bins = [0,4,8,12,16,20,24]
labels = ['Late Night', 'Early Morning','Morning','Noon','Eve','Night']
df_daily_new['session'] = pd.cut(df_daily_new['hour'], bins=bins, labels=labels, include_lowest=True)

In [487]:
df_daily_new = df_daily_new[~df_daily_new['datetime'].duplicated(keep = 'first')]
df_daily_new.head()

,datetime,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics,date,year,dayOfYear,month,monthName,week,day,dayName,hour,minute,dayOfWeek,weekend,time,time_Str,dayMonth,hourMinute,session
0,2020-03-15 00:00:00,1.584223e+12,3482.0,0.0,0.0,3482.0,0.0,0.0,0.0,"[7.9, 853.1, -554.9, -224.7, -163.6, 2674.0, 8...","[39.1, 425.6, 244.0, 796.8, 1134.5, 1219.7, 91...","[245.3, None, None]","[245.3, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...",2020-03-15,2020,75,3,March,11,15,Sunday,0,0,6,1,00:00:00,00:00:00,03-15,00:00,Late Night
1,2020-03-15 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-15,2020,75,3,March,11,15,Sunday,1,0,6,1,01:00:00,01:00:00,03-15,01:00,Late Night
2,2020-03-15 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-15,2020,75,3,March,11,15,Sunday,2,0,6,1,02:00:00,02:00:00,03-15,02:00,Late Night
3,2020-03-15 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-15,2020,75,3,March,11,15,Sunday,3,0,6,1,03:00:00,03:00:00,03-15,03:00,Late Night
4,2020-03-15 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-15,2020,75,3,March,11,15,Sunday,4,0,6,1,04:00:00,04:00:00,03-15,04:00,Late Night

In [488]:
df_daily_new.columns

Index(['datetime', 'timestamp', 'consumption', 'solar', 'alwaysOn',
       'gridImport', 'gridExport', 'selfConsumption', 'selfSufficiency',
       'active', 'reactive', 'voltages', 'phaseVoltages', 'currentHarmonics',
       'voltageHarmonics', 'date', 'year', 'dayOfYear', 'month', 'monthName',
       'week', 'day', 'dayName', 'hour', 'minute', 'dayOfWeek', 'weekend',
       'time', 'time_Str', 'dayMonth', 'hourMinute', 'session'],
      dtype='object')

In [489]:
#Reorder columns
# Put non-ML friendly columns first - they may get dropped when loading into models
col_order = ['datetime', 'consumption_kWh', 'date', 'year', 'dayMonth', 'time', 'time_Str', 'hourMinute', 'session', 'monthName', 'dayName', 
             'dayOfYear', 'week', 'month', 'day', 'hour', 'minute', 'dayOfWeek', 'weekend', 'workingDay']
df_daily_new =df_daily_new.reindex(columns=col_order)

Monthly Wrangling

In [490]:
asset = "/content/drive/MyDrive/NEEDENERGY/data_monthly_id_47803.csv"

df_monthly = load_data(asset)

In [491]:
df_monthly.head()

,date,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-01,1583013600000,1179802.500,388470.400,346740.800,791327.100,0.0,100.0,32.93,"[531.3, 16889.3, -555.0, -224.7, -163.6, 37998...","[2318.9, 4046.1, 245.9, 796.8, 1134.5, 17050.9...","[245.2, None, None]","[245.2, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-04-01,1585692000000,1804465.559,402066.023,925839.044,1402399.436,0.0,100.0,22.28,"[1435.8, 32795.7, -1944.1, None, None, None, N...","[4599.8, 8316.3, 828.1, None, None, None, None...","[243.0, None, None]","[243.0, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,2020-05-01,1588284000000,1944237.003,518593.738,955550.728,1425646.164,0.0,100.0,26.67,"[2626.8, 39047.3, -6846.1, None, None, None, N...","[5027.5, 11517.4, 3325.6, None, None, None, No...","[243.3, None, None]","[243.3, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
3,2020-06-01,1590962400000,2153164.738,895372.822,957943.678,1257791.216,0.0,100.0,41.58,"[3960.6, 135469.3, -103141.7, None, None, None...","[5704.6, 67130.6, 55004.4, None, None, None, N...","[239.7, None, None]","[239.7, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
4,2020-07-01,1593554400000,2315455.680,950757.285,875789.005,1364694.795,0.0,100.0,41.06,"[2560.5, 109309.6, -77368.3, None, None, None,...","[5116.8, 50605.1, 42239.5, None, None, None, N...","[237.6, None, None]","[237.6, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

In [492]:
#basic profiling
df_monthly.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12 entries, 0 to 11
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              12 non-null     datetime64[ns]
 1   timestamp         12 non-null     int64
 2   consumption       12 non-null     float64
 3   solar             12 non-null     float64
 4   alwaysOn          12 non-null     float64
 5   gridImport        12 non-null     float64
 6   gridExport        12 non-null     float64
 7   selfConsumption   12 non-null     float64
 8   selfSufficiency   12 non-null     float64
 9   active            12 non-null     object
 10  reactive          12 non-null     object
 11  voltages          12 non-null     object
 12  phaseVoltages     12 non-null     object
 13  currentHarmonics  12 non-null     object
 14  voltageHarmonics  12 non-null     object
dtypes: datetime64[ns](1), float64(7), int64(1), object(6)
memory usage: 1.5+ KB

In [493]:
#statistcal summary
df_monthly.describe

<bound method NDFrame.describe of          date      timestamp  consumption       solar     alwaysOn  \
0  2020-03-01  1583013600000  1179802.500  388470.400   346740.800
1  2020-04-01  1585692000000  1804465.559  402066.023   925839.044
2  2020-05-01  1588284000000  1944237.003  518593.738   955550.728
3  2020-06-01  1590962400000  2153164.738  895372.822   957943.678
4  2020-07-01  1593554400000  2315455.680  950757.285   875789.005
5  2020-08-01  1596232800000  1794921.591  512289.482   937842.229
6  2020-09-01  1598911200000  2107164.671  664597.756  1122638.378
7  2020-10-01  1601503200000  2347974.402  636391.709  1164159.215
8  2020-11-01  1604181600000  2535679.307  688904.711  1188357.784
9  2020-12-01  1606773600000  2439129.170  589920.157  1263850.108
10 2021-01-01  1609452000000  2232866.229  551775.764  1045223.515
11 2021-02-01  1612130400000   928220.438  208491.292   320518.523

     gridImport  gridExport  selfConsumption  selfSufficiency  \
0    791327.100         0.0            100.0            32.93
1   1402399.436         0.0            100.0            22.28
2   1425646.164         0.0            100.0            26.67
3   1257791.216         0.0            100.0            41.58
4   1364694.795         0.0            100.0            41.06
5   1282632.208         0.0            100.0            28.54
6   1442565.715         0.0            100.0            31.54
7   1711584.893         0.0            100.0            27.10
8   1846771.796         0.0            100.0            27.17
9   1849210.513         0.0            100.0            24.19
10  1681088.064         0.0            100.0            24.71
11   719730.146         0.0            100.0            22.46

                                               active  \
0   [531.3, 16889.3, -555.0, -224.7, -163.6, 37998...
1   [1435.8, 32795.7, -1944.1, None, None, None, N...
2   [2626.8, 39047.3, -6846.1, None, None, None, N...
3   [3960.6, 135469.3, -103141.7, None, None, None...
4   [2560.5, 109309.6, -77368.3, None, None, None,...
5   [1007.3, 62835.6, -30999.7, None, None, None, ...
6   [974.0, 34519.4, -3750.1, None, None, None, No...
7   [1004.3, 32218.2, -742.5, None, None, None, No...
8   [21397.7, 42783.3, -10201.9, None, None, None,...
9   [1008.6, 31341.0, -85.2, None, None, None, Non...
10  [1003.9, 31724.3, -195.7, None, None, None, No...
11  [390.5, 12146.5, -58.3, None, None, None, None...

                                             reactive             voltages  \
0   [2318.9, 4046.1, 245.9, 796.8, 1134.5, 17050.9...  [245.2, None, None]
1   [4599.8, 8316.3, 828.1, None, None, None, None...  [243.0, None, None]
2   [5027.5, 11517.4, 3325.6, None, None, None, No...  [243.3, None, None]
3   [5704.6, 67130.6, 55004.4, None, None, None, N...  [239.7, None, None]
4   [5116.8, 50605.1, 42239.5, None, None, None, N...  [237.6, None, None]
5   [4197.4, 26246.5, 15439.8, None, None, None, N...  [240.1, None, None]
6   [4033.8, 9481.1, 1905.3, None, None, None, Non...  [240.1, None, None]
7   [2789.5, 7743.8, 255.4, None, None, None, None...  [238.2, None, None]
8   [6252.1, 13015.6, 4353.1, None, None, None, No...  [240.5, None, None]
9   [-4173.3, 7220.0, 20.4, None, None, None, None...  [239.2, None, None]
10  [-4191.3, 7442.0, 11.2, None, None, None, None...  [240.5, None, None]
11  [-1645.6, 2856.0, 1.8, None, None, None, None,...  [241.7, None, None]

          phaseVoltages                                   currentHarmonics  \
0   [245.2, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
1   [243.0, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
2   [243.3, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
3   [239.7, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
4   [237.6, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
5   [240.1, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
6   [240.1, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
7   [238.2, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
8   [240.5, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
9   [239.2, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
10  [240.5, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...
11  [241.7, None, None]  [[], [], [], [], [], [], [], [], [], [], [], [...

                                     voltageHarmonics
0   [[], [], [], [], [], [], [], [], [], [], [], [...
1   [[], [], [], [], [], [], [], [], [], [], [], [...
2   [[], [], [], [], [], [], [], [], [], [], [], [...
3   [[], [], [], [], [], [], [], [], [], [], [], [...
4   [[], [], [], [], [], [], [], [], [], [], [], [...
5   [[], [], [], [], [], [], [], [], [], [], [], [...
6   [[], [], [], [], [], [], [], [], [], [], [], [...
7   [[], [], [], [], [], [], [], [], [], [], [], [...
8   [[], [], [], [], [], [], [], [], [], [], [], [...
9   [[], [], [], [], [], [], [], [], [], [], [], [...
10  [[], [], [], [], [], [], [], [], [], [], [], [...
11  [[], [], [], [], [], [], [], [], [], [], [], [...  >

In [494]:
#List of features
df_monthly.columns

Index(['date', 'timestamp', 'consumption', 'solar', 'alwaysOn', 'gridImport',
       'gridExport', 'selfConsumption', 'selfSufficiency', 'active',
       'reactive', 'voltages', 'phaseVoltages', 'currentHarmonics',
       'voltageHarmonics'],
      dtype='object')

In [495]:
df_monthly_new = df_monthly.copy()

In [496]:
df_monthly_new.head()

,date,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-01,1583013600000,1179802.500,388470.400,346740.800,791327.100,0.0,100.0,32.93,"[531.3, 16889.3, -555.0, -224.7, -163.6, 37998...","[2318.9, 4046.1, 245.9, 796.8, 1134.5, 17050.9...","[245.2, None, None]","[245.2, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-04-01,1585692000000,1804465.559,402066.023,925839.044,1402399.436,0.0,100.0,22.28,"[1435.8, 32795.7, -1944.1, None, None, None, N...","[4599.8, 8316.3, 828.1, None, None, None, None...","[243.0, None, None]","[243.0, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
2,2020-05-01,1588284000000,1944237.003,518593.738,955550.728,1425646.164,0.0,100.0,26.67,"[2626.8, 39047.3, -6846.1, None, None, None, N...","[5027.5, 11517.4, 3325.6, None, None, None, No...","[243.3, None, None]","[243.3, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
3,2020-06-01,1590962400000,2153164.738,895372.822,957943.678,1257791.216,0.0,100.0,41.58,"[3960.6, 135469.3, -103141.7, None, None, None...","[5704.6, 67130.6, 55004.4, None, None, None, N...","[239.7, None, None]","[239.7, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
4,2020-07-01,1593554400000,2315455.680,950757.285,875789.005,1364694.795,0.0,100.0,41.06,"[2560.5, 109309.6, -77368.3, None, None, None,...","[5116.8, 50605.1, 42239.5, None, None, None, N...","[237.6, None, None]","[237.6, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."

In [497]:
#Check for duplicates
df_monthly_new.index[df_monthly_new['date'].duplicated(keep=False)==True]

Int64Index([], dtype='int64')

In [498]:
# Check for missing info using Missingno Package
msno = import_package('missingno')
msno.matrix(df_monthly_new)

missingno Version: 0.4.2

/usr/local/lib/python3.7/dist-packages/missingno/missingno.py:50: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure(figsize=figsize)

In [499]:
# Check if there are any periods of zero values
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
features = df_monthly_new.select_dtypes(include=numerics).columns 
for feature in features: 
    zero_results = df_monthly_new[df_monthly_new[feature]==0]
zero_results.head()

Empty DataFrame
Columns: [date, timestamp, consumption, solar, alwaysOn, gridImport, gridExport, selfConsumption, selfSufficiency, active, reactive, voltages, phaseVoltages, currentHarmonics, voltageHarmonics]
Index: []

In [500]:
# Check for any missing time steps, create hourly datetime index and compare to length of dataframe
start = df_monthly_new['date'].min()
end = df_monthly_new['date'].max()
full_index = pd.date_range(start, end, freq='H')
len(full_index) == len(df_monthly_new)

False

In [501]:
df_monthly_new.set_index('date', inplace = True)
df_monthly_new = df_monthly_new.reindex(full_index)
df_monthly_new.index

DatetimeIndex(['2020-03-01 00:00:00', '2020-03-01 01:00:00',
               '2020-03-01 02:00:00', '2020-03-01 03:00:00',
               '2020-03-01 04:00:00', '2020-03-01 05:00:00',
               '2020-03-01 06:00:00', '2020-03-01 07:00:00',
               '2020-03-01 08:00:00', '2020-03-01 09:00:00',
               ...
               '2021-01-31 15:00:00', '2021-01-31 16:00:00',
               '2021-01-31 17:00:00', '2021-01-31 18:00:00',
               '2021-01-31 19:00:00', '2021-01-31 20:00:00',
               '2021-01-31 21:00:00', '2021-01-31 22:00:00',
               '2021-01-31 23:00:00', '2021-02-01 00:00:00'],
              dtype='datetime64[ns]', length=8089, freq='H')

In [502]:
#Have a look at missing values
print(f"{df_monthly_new.isnull().sum()}\n\n")
print(f"Percentage of missing values:\t{(df_monthly_new['consumption'].isnull().sum()/df_monthly_new['timestamp'].count())*100}")

timestamp           8077
consumption         8077
solar               8077
alwaysOn            8077
gridImport          8077
gridExport          8077
selfConsumption     8077
selfSufficiency     8077
active              8077
reactive            8077
voltages            8077
phaseVoltages       8077
currentHarmonics    8077
voltageHarmonics    8077
dtype: int64


Percentage of missing values:	67308.33333333334

In [503]:
df_monthly_new.reset_index(inplace=True)
df_monthly_new.rename(columns = {'index':'datetime'}, inplace = True)
df_monthly_new.head()

,datetime,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics
0,2020-03-01 00:00:00,1.583014e+12,1179802.5,388470.4,346740.8,791327.1,0.0,100.0,32.93,"[531.3, 16889.3, -555.0, -224.7, -163.6, 37998...","[2318.9, 4046.1, 245.9, 796.8, 1134.5, 17050.9...","[245.2, None, None]","[245.2, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [..."
1,2020-03-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-03-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-03-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-03-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [504]:
#Feature Engineering of Time Series
#df_5min_new['datetime']=pd.to_datetime(df_5min_new['date'])
df_monthly_new['date'] = df_monthly_new['datetime'].dt.strftime('%Y-%m-%d')
df_monthly_new['year'] = df_monthly_new['datetime'].dt.year 
df_monthly_new['dayOfYear'] = df_monthly_new['datetime'].dt.dayofyear
df_monthly_new['month'] = df_monthly_new['datetime'].dt.month 
df_monthly_new['monthName'] = pd.DatetimeIndex(df_monthly_new['datetime']).month_name()
df_monthly_new['week'] = df_monthly_new['datetime'].dt.week
df_monthly_new['day'] = df_monthly_new['datetime'].dt.day
df_monthly_new['dayName'] = pd.DatetimeIndex(df_monthly_new['datetime']).day_name()
df_monthly_new['hour'] = df_monthly_new['datetime'].dt.hour
df_monthly_new['minute'] = df_monthly_new['datetime'].dt.minute
df_monthly_new['dayOfWeek'] = df_monthly_new['datetime'].dt.dayofweek
df_monthly_new['weekend'] = df_monthly_new['dayOfWeek'].apply(lambda x: 1 if x >= 5 else 0)
df_monthly_new['time'] = df_monthly_new['datetime'].dt.time 
df_monthly_new['time_Str'] = df_monthly_new['datetime'].dt.time.astype(str)   
df_monthly_new['dayMonth'] = df_monthly_new["datetime"].dt.strftime('%m-%d')
df_monthly_new['hourMinute'] = df_monthly_new["datetime"].dt.strftime('%H:%M')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.

In [505]:
bins = [0,4,8,12,16,20,24]
labels = ['Late Night', 'Early Morning','Morning','Noon','Eve','Night']
df_monthly_new['session'] = pd.cut(df_monthly_new['hour'], bins=bins, labels=labels, include_lowest=True)

In [506]:
df_monthly_new = df_monthly_new[~df_monthly_new['datetime'].duplicated(keep = 'first')]
df_monthly_new.head()

,datetime,timestamp,consumption,solar,alwaysOn,gridImport,gridExport,selfConsumption,selfSufficiency,active,reactive,voltages,phaseVoltages,currentHarmonics,voltageHarmonics,date,year,dayOfYear,month,monthName,week,day,dayName,hour,minute,dayOfWeek,weekend,time,time_Str,dayMonth,hourMinute,session
0,2020-03-01 00:00:00,1.583014e+12,1179802.5,388470.4,346740.8,791327.1,0.0,100.0,32.93,"[531.3, 16889.3, -555.0, -224.7, -163.6, 37998...","[2318.9, 4046.1, 245.9, 796.8, 1134.5, 17050.9...","[245.2, None, None]","[245.2, None, None]","[[], [], [], [], [], [], [], [], [], [], [], [...","[[], [], [], [], [], [], [], [], [], [], [], [...",2020-03-01,2020,61,3,March,9,1,Sunday,0,0,6,1,00:00:00,00:00:00,03-01,00:00,Late Night
1,2020-03-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-01,2020,61,3,March,9,1,Sunday,1,0,6,1,01:00:00,01:00:00,03-01,01:00,Late Night
2,2020-03-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-01,2020,61,3,March,9,1,Sunday,2,0,6,1,02:00:00,02:00:00,03-01,02:00,Late Night
3,2020-03-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-01,2020,61,3,March,9,1,Sunday,3,0,6,1,03:00:00,03:00:00,03-01,03:00,Late Night
4,2020-03-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-01,2020,61,3,March,9,1,Sunday,4,0,6,1,04:00:00,04:00:00,03-01,04:00,Late Night

In [507]:
df_monthly_new.columns

Index(['datetime', 'timestamp', 'consumption', 'solar', 'alwaysOn',
       'gridImport', 'gridExport', 'selfConsumption', 'selfSufficiency',
       'active', 'reactive', 'voltages', 'phaseVoltages', 'currentHarmonics',
       'voltageHarmonics', 'date', 'year', 'dayOfYear', 'month', 'monthName',
       'week', 'day', 'dayName', 'hour', 'minute', 'dayOfWeek', 'weekend',
       'time', 'time_Str', 'dayMonth', 'hourMinute', 'session'],
      dtype='object')

In [508]:
#Reorder columns
# Put non-ML friendly columns first - they may get dropped when loading into models
col_order = ['datetime', 'consumption_kWh', 'date', 'year', 'dayMonth', 'time', 'time_Str', 'hourMinute', 'session', 'monthName', 'dayName', 
             'dayOfYear', 'week', 'month', 'day', 'hour', 'minute', 'dayOfWeek', 'weekend', 'workingDay']
df_monthly_new =df_monthly_new.reindex(columns=col_order)

In [509]:
#to CSV
df_5min_new.to_csv('NeedEnergyAPI_5min.csv',index=False)
df_hourly_new.to_csv('NeedEnergyAPI_hourly.csv',index=False)
df_daily_new.to_csv('NeedEnergyAPI_daily.csv',index=False)
df_monthly_new.to_csv('NeedEnergyAPI_monthly.csv',index=False)

Missing Data Imputation

In [415]:
#Investigate where missing row/hours are
# Consumption null values occur in continuous period 
# Do not use simple forward fill, impute average day profile for both days
#df_5min_new[df_5min_new['consumption'].isnull()]

In [416]:
#Check out missing period
#plt.plot(df_5min_new[(df_5min_new['datetime']>='2020-05-20 00:00:00') & (df_5min_new['datetime']<='2020-05-30 00:00:00')]['consumption'])

In [417]:
#Get average Weekday and Weekend profiles for May and impute profile
# create_monthly_profiles(df, column)
#profile_df = create_monthly_profiles(df_5min_new, 'consumption')
#profile_df

In [418]:
#weather_df = pd.read_csv("/Users/nancy/Downloads/Data/Test/data/Harare_Hourly_Weather_2005-2021.csv")
#weather_df = pd.read_csv("https://raw.githubusercontent.com/OmdenaAI/NeedEnergy/Task-2-Data-Wrangling/data/weather_data/Harare_Hourly_Weather_2005-2021.csv?token=AGZP7CAUIRLTZHJM6WLHASTAHD3Z2")
#weather_df.head()

HTTPError: ignored

In [ ]:
# Temperature, humidity and cloud cover are wanted variables
#weather_df.columns

In [ ]:
#weather_df['datetime'] = weather_df['datetime'].apply(lambda x: datetime.strptime(x,'%Y-%m-%d %H:%M:%S %z %Z').strftime('%Y-%m-%d %H:%M:%S'))
#weather_df.head()

In [ ]:

# Slice datarame for 2020 onwards
#weather_df = weather_df.loc[pd.to_datetime(weather_df['datetime']).dt.year >= 2020]
#weather_df

In [ ]:
# Check there are no missing rows/hours
weather_start = weather_df['datetime'].min()
weather_end = weather_df['datetime'].max()
weather_full_index = pd.date_range(weather_start, weather_end, freq='H')
len(weather_full_index) == len(weather_df)

In [ ]:
weather_df.set_index('datetime', inplace = True)
weather_df = weather_df.reindex(weather_full_index)
weather_df.index

In [ ]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
weather_features = weather_df.select_dtypes(include=numerics).columns 
for feature in weather_features:
    weather_df[feature] = weather_df[feature].replace(0,np.nan)
    weather_df[feature] = weather_df[feature].fillna(method = 'bfill')   
weather_df.reset_index(inplace = True)
weather_df.rename(columns = {'index':'datetime'}, inplace = True)
weather_df.head()

In [ ]:
#check the weather data is ok
# Negative value for cloud cover!!!
weather_df.describe()

In [ ]:
weather_df['temp'].plot()

In [ ]:
weather_df['humidity'].plot()

In [ ]:


weather_df['clouds_all'].plot()

In [ ]:

weather_df[weather_df['clouds_all']<0]

In [ ]:

# Check period where cloud cover is less than 0
weather_df[(weather_df['datetime']>='2020-11-01 04:00:00') & (weather_df['datetime']<='2020-11-01 10:00:00')]

In [ ]:
# Use simple forward fill to replace negative cloud cover values
weather_df['clouds_all']=weather_df['clouds_all'].mask(weather_df['clouds_all']<0).ffill(downcast='infer')

In [ ]:

weather_df['clouds_all'].plot()

In [ ]:

# Rename and divide by 100 to make it more ML friendly
weather_df['clouds_all'] = weather_df['clouds_all']/100
weather_df.rename(columns={'clouds_all':'cloud_cover'}, inplace=True)
# Temperature in degrees C, rename with units
weather_df.rename(columns={'temp':'temp_degreeC'}, inplace=True)
# Humidity is relative humidity as a %
# Rename and divide by 100 to make it more ML friendly
weather_df['humidity'] = weather_df['humidity']/100
weather_df.rename(columns={'humidity':'rel_humidity'}, inplace=True)